<?php
//Name:RAMLOCHUND Gitendrajeet 
//Project: UDM Online Student Lodging Accommodation Management System (OSLAMS)
//Scope: New user Registration(First Time User for the OSLAMS).

  //Require Class user to be able to create objects
  require_once(__DIR__.'/controller/user.php');
  //Function to Start Session
  session_start();

  //Variable $error used as place holder for future errors that will be generated by the system as at now its an empty String.
  $error="";

  //POST will collect Data when btnSubmit is pressed by user.
  if (isset($_POST["btnSubmit"]))
  {       
       //Try and catch has been used here to catch possible erros which might encounter Eg. Where duplication of user on system.
          try{

             //Creating an object $usr from Class user
             $usr = new user();

             //Varaiable to hold data to be used in function
             $uname = $_POST['uname'];
             $pwd = $_POST['pwd'];
             $surname= $_POST['surname'];
             $name= $_POST['name'];
             $cat = $_POST['cat'];

            //Creation of Session variable where username has been assigned to it
             $_SESSION['username']=$uname;

              //Calling a function addUser from User Class for Creating a New user and send the data to database
              $usr->registerUser($surname,$name,$cat,$uname,$pwd);
              $error="Successfully added the new user " . $_POST['name'];

              //Switch Case has been implemented to redirect user upon Category selection for further registration process
              switch($cat)
                  {
                    case "Landlord":
                      header("Location:landlord/landlordPersonal.php");
                      break;
                    case "Tenant":
                      header("Location:tenant/tenantPersonal.php");
                      break;
                    case "Student":
                      header("Location:index.php");
                      break;
                    default:
                      header("Location:index.php");
                  }
            }
            //This function will catch all Errors and display a custom message.
          Catch(PDOException $e) 
            {
              //Variable hold custom messsage to display in case of error occur for user already exist
              $error="Username already Exist on UDM OSLAM System";
            }   
}
?>
<!DOCTYPE html>
<html>
<title>UDM OSLAMS Welcome | First Time User Registration </title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="images/favicon.png">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
<style>
  html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>

<body class="w3-light-grey">

<!-- Top container -->
<div class="w3-bar w3-top w3-white w3-large" style="z-index:3">
   <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-blue" onclick="w3_open();"><i class="fa fa-bars"></i> Menu</button>
    <span class="w3-bar-item w3-right"><img src="images/minLogo.png"   alt="" >&nbsp; &nbsp;<h3 style="display: inline-block">Online Student Lodging Accomodation Management System</h3></span>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-light w3-animate-left" style="z-index:4;width:300px;" id="mySidebar">
    <div class="w3-container">
      <center><img src="images/firstTime.png" class="img-responsive" alt="" style="width:80px;"></center>
    <br>
      <span>Welcome, <strong>User</strong></span><br>
    </div>
  </div>
  <hr>
  <div class="w3-container">
      <h5>UDM OSLAMS | First Time User Registration Form</h5>
  </div>
  <div class="w3-bar-block">
      <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
      <p class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-user-circle-o"></i>  User Registration  </p>
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">

  <!-- Header -->
  <header class="w3-container" style="padding-top:73px">
     <h4></strong>&nbsp;<b><i class="fa fa-tachometer" aria-hidden="true"></i> | First Time User Creation</b></h4>
  </header>

<!-- START of Container Which will Display the form for New User Registration -->
<br>
<div class="container">
    <div class="form">
        <div class="panel panel-primary shadow">
          <div class="panel-heading">
            
              <h3 class="text-center">New User Registeration Form OSLAMS</h3>
          </div>
        <div class="panel-body">
          <form method="post" enctype="multipart/form-data">

            <?php if (isset($_POST["btnSubmit"])) {?>
            <div class="alert alert-info" role="alert">
               <strong><?php echo $error; ?></strong> 
             </div>
                <?php }?>


            <div class="form-group">
              <label for="">Surname</label>
              <input type="text" pattern="[a-zA-Z]+" oninvalid="setCustomValidity('Please enter on alphabets only and Spaces are not allowed. ')" class="form-control" name="surname" required></input>
            </div>

            <div class="form-group">
              <label for="">Name</label>
              <input type="text" pattern="[a-zA-Z]+" oninvalid="setCustomValidity('Please enter on alphabets only and Spaces are not allowed. ')" class="form-control" name="name" required></input>
            </div>

           <div class="form-group">
                <label for="">Category</label>
                 <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="cat" id="cat1" value="Landlord" checked>
                      <label class="form-check-label" for="inlineRadio1">Landlord</label>
                 </div>
                <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="cat" id="cat2" value="Student">
                      <label class="form-check-label" for="inlineRadio2">Prospect Student (New Students Only)</label>
                </div>
                <div class="form-check form-check-inline">
                       <input class="form-check-input" type="radio" name="cat" id="cat2" value="Tenant">
                       <label class="form-check-label" for="inlineRadio2">Enrolled Student (Also Known As Tenant)</label>
                </div>
            </div>

            <div class="form-group">
                       <label for="">Username</label>
                       <input type="text" class="form-control" name="uname" required></input>
            </div>

            <div class="form-group">
                       <label for="">Password</label>
                       <input type="password" class="form-control" name="pwd" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required></input>
            </div>

            <button type="submit" id="submit-button" class="btn btn-primary" name="btnSubmit">Submit</button>&nbsp;&nbsp;
            <input type="reset" class="btn btn-danger" value="Reset"/>&nbsp;&nbsp;
            <button type="cancel" class="btn btn-warning" onclick="javascript:window.location='index.php';">Cancel</button>
        </div>
        </form>
      </div>
    </div>
  </div>

 <!-- Footer -->
  <footer class="w3-container w3-padding-16 w3-light-grey">
    <center><h5>&copy; 2021 UDM OSLAMS | By Gitendra</h5></center>
  </footer>
  <!-- End page content -->

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>
</body>
</html>